### PR TITLE
Fix restart flake

### PR DESCRIPTION
**Pull request by rustyrussell**
This is causing a CI flake, because our "do we really need to restart?" logic is wrong.  @vincenzopalazzo changed the block number when he extracted the backend (which was wrong), but the test for mempool was always backwards!

And updated documentation, too.

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
ack https://github.com/rustyrussell/lnprototest/pull/20/commits/9beb1677d61534a34a4ab365cb79b84376b549fc

LGTM but I have a couple of points that I want to point out anyway.

- Why do we need that the block height is different from 102? is possible that we call restart, or better a test call restart when the block are `<= 101`? I was thinking that maybe an `> 101` is better to avoid other changes to this side in the future?
-  I'm not able to catch when the condition evaluate to false of this if `if self.rpc.getblockcount() != 101 or self.rpc.getrawmempool() != []:` is useful. Why we can not restart anyway?

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/rustyrussell/lnprototest/pull/20/commits/9beb1677d61534a34a4ab365cb79b84376b549fc

LGTM but I have a couple of points that I want to point out anyway.

- Why do we need that the block height is different from 102? is possible that we call restart, or better a test call restart when the block are `<= 101`? I was thinking that maybe an `> 101` is better to avoid other changes to this side in the future?
-  I'm not able to catch when the condition evaluate to false of this if `if self.rpc.getblockcount() != 101 or self.rpc.getrawmempool() != []:` is useful. Why we can not restart anyway?

**Comment by rustyrussell** [comment]
If it's not exactly 101 it's weird, since we mine that many on startup.

If there's anything in the mempool, we still need to restart, otherwise we can get clashes

**Comment by vincenzopalazzo** [comment]
>If there's anything in the mempool, we still need to restart, otherwise we can get clashes

Ah damn, @vincenzopalazzo was slow to loading corner case :) sorry for that

**Pull request merged**
